name: my_app2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:

  android: true
  ios: true
  web: true

  color: "#FFFFFF"
 # background_image: 
  image: "lib/screens/images/luncher.png"

 # android_gravity: center
 # ios_content_mode: center
 # web_image_mode: center

 # color_dark:
 # background_image_dark:
 # image_dark:

 # fullscreen: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lib/screens/images/1a49d5b78fc02eeeefeee667bb2369d3.jpg
    - lib/screens/images/IMG_8477.PNG
    - lib/screens/images/IMG_8478.PNG
    - lib/screens/images/IMG_8480.WEBP
    - lib/screens/images/IMG_8482.PNG
    - lib/screens/images/IMG-20220820-WA0083.jpg
    - lib/screens/images/IMG-20220820-WA0025.jpg
    - lib/screens/images/IMG-20220820-WA0063.jpg
    - lib/screens/images/IMG-20220820-WA0040.jpg
    - lib/screens/images/IMG-20220820-WA0026.jpg
    - lib/screens/images/IMG-20220820-WA0032.jpg
    - lib/screens/images/IMG-20220820-WA0023.jpg
    - lib/screens/images/IMG-20220820-WA0030.jpg
    - lib/screens/images/IMG-20220820-WA0077.jpg
    - lib/screens/images/IMG-20220820-WA0073.jpg
    - lib/screens/images/IMG-20220820-WA0079.jpg
    - lib/screens/images/IMG-20220820-WA0080.jpg
    - lib/screens/images/IMG-20220820-WA0081.jpg
    - lib/screens/images/IMG-20220820-WA0056.jpg
    - lib/screens/images/IMG-20220820-WA0039.jpg
    - lib/screens/images/IMG-20220820-WA0037.jpg
    - lib/screens/images/IMG-20220820-WA0053.jpg
    - lib/screens/images/IMG-20220820-WA0058.jpg
    - lib/screens/images/IMG-20220820-WA0067.jpg
    - lib/screens/images/IMG-20220820-WA0043.jpg
    - lib/screens/images/IMG-20220820-WA0044.jpg
    - lib/screens/images/IMG-20220820-WA0078.jpg
    - lib/screens/images/IMG-20220822-WA0097.jpg
    - lib/screens/images/IMG-20220820-WA0028.jpg
    - lib/screens/images/IMG-20220820-WA0029.jpg
    - lib/screens/images/IMG-20220820-WA0031.jpg
    - lib/screens/images/IMG-20220823-WA0005.jpg
    - lib/screens/images/IMG-20220823-WA0007.jpg
    - lib/screens/images/IMG-20220820-WA0062.jpg
    - lib/screens/images/IMG-20220820-WA0072.jpg
    - lib/screens/images/IMG-20220820-WA0074.jpg
    - lib/screens/images/IMG-20220820-WA0082.jpg
    - lib/screens/images/IMG-20220820-WA0047.jpg
    - lib/screens/images/Screenshot (135).png
    - lib/screens/images/Screenshot (136).png
    - lib/screens/images/Screenshot (137).png
    - lib/screens/images/Screenshot (138).png
    - lib/screens/images/Screenshot (141).png
    - lib/screens/images/Screenshot (140).png
    - lib/screens/images/Screenshot (142).png
    - lib/screens/images/Screenshot (143).png
    - lib/screens/images/d192c42b6d6879fc43643c7f0791f65a.jpg
    - lib/screens/images/bbc9888ca93cb40f08b053f124fdb25b.jpg
    - lib/screens/images/1ec31fddba8eea66a8b45bf06b8bc1a2.jpg
    - lib/screens/images/2516b2b8995c5eb686986e7d25d04cb7.jpg
    - lib/screens/images/9b61a8c75a4a7d08c8c8ee99c99f64bb.jpg
    - lib/screens/images/6fc2c904f62233cf5a42dc6761d93ae1.jpg
    - lib/screens/images/4201ed848f08785454101b58ecc15c9e.jpg
    - lib/screens/images/9235f9a8955e72156e5662c67f9fb11f.jpg
    - lib/screens/images/7211b33a871790124c92521903b61fce.jpg
    - lib/screens/images/IMG-20220820-WA0061.jpg
    - lib/screens/images/IMG-20220820-WA0065.jpg
    - lib/screens/images/IMG-20220820-WA0070.jpg
    - lib/screens/images/IMG-20220820-WA0059.jpg
    - lib/screens/images/luncher.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
